# Generated by Django 5.1.15 on 2025-12-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chint_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('parent_id', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('vendor_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name_full', models.TextField(blank=True, default='')),
                ('name_short', models.TextField(blank=True, default='')),
                ('picture_url', models.URLField(blank=True, default='', max_length=500)),
                ('images', models.JSONField(blank=True, default=list)),
                ('source_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('parent_id', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
