# Generated by Django 5.1.15 on 2025-12-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='source_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
