# Generated by Django 5.1.15 on 2025-12-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productgroup_source_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_full',
            new_name='name_full_az',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_short',
            new_name='name_full_en',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='name_full_ka',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='name_full_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='name_short_az',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='name_short_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='name_short_ka',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='name_short_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='name_az',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='name_ka',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
