# Generated by Django 5.1.15 on 2025-12-25 07:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_full_product_name_full_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase English (a-z, 0-9, hyphens). Example: low-voltage-equipment', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_az', models.CharField(max_length=255)),
                ('name_ka', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/categories/')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.catalogcategory')),
            ],
            options={
                'ordering': ('sort_order', 'name_ru'),
            },
        ),
    ]
