# Generated by Django 5.1.15 on 2025-12-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_catalogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='product_groups',
            field=models.ManyToManyField(blank=True, related_name='catalog_categories', to='api.productgroup'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/product-groups/'),
        ),
    ]
