# Generated by Django 5.1.15 on 2026-02-18 10:06

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeaturedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.UUIDField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HomeRecommendedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('background', models.ImageField(upload_to='home/slider/backgrounds/')),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='home/slider/images/')),
                ('tag_ru', models.CharField(blank=True, default='', max_length=255)),
                ('tag_en', models.CharField(blank=True, default='', max_length=255)),
                ('tag_az', models.CharField(blank=True, default='', max_length=255)),
                ('tag_ka', models.CharField(blank=True, default='', max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_az', models.CharField(blank=True, default='', max_length=255)),
                ('title_ka', models.CharField(blank=True, default='', max_length=255)),
                ('text_ru', models.TextField(blank=True, default='')),
                ('text_en', models.TextField(blank=True, default='')),
                ('text_az', models.TextField(blank=True, default='')),
                ('text_ka', models.TextField(blank=True, default='')),
                ('button_ru', models.CharField(blank=True, default='', max_length=255)),
                ('button_en', models.CharField(blank=True, default='', max_length=255)),
                ('button_az', models.CharField(blank=True, default='', max_length=255)),
                ('button_ka', models.CharField(blank=True, default='', max_length=255)),
                ('button_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home slider',
                'verbose_name_plural': 'Home sliders',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LibraryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_index', models.PositiveSmallIntegerField(choices=[(0, 'Мастер-каталог (New)'), (1, 'Техническая документация'), (2, 'Рекламные материалы'), (3, 'Сертификаты'), (4, 'Для проектировщиков')])),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_az', models.CharField(blank=True, default='', max_length=255)),
                ('title_ka', models.CharField(blank=True, default='', max_length=255)),
                ('file_ru', models.FileField(upload_to='library/ru/')),
                ('file_en', models.FileField(upload_to='library/en/')),
                ('file_az', models.FileField(blank=True, null=True, upload_to='library/az/')),
                ('file_ka', models.FileField(blank=True, null=True, upload_to='library/ka/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('tab_index', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=180, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase English.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_az', models.CharField(blank=True, default='', max_length=255)),
                ('title_ka', models.CharField(blank=True, default='', max_length=255)),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('body_az', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('body_ka', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('cover', models.ImageField(upload_to='news/covers/')),
                ('published_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-published_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('en', models.TextField(blank=True, default='')),
                ('ru', models.TextField(blank=True, default='')),
                ('az', models.TextField(blank=True, default='')),
                ('ka', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.news')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
