# Generated by Django 5.1.15 on 2026-02-18 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_propertyvalue_value_az_propertyvalue_value_en_and_more'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homerecommendedproduct',
            name='product_id',
        ),
        migrations.AddField(
            model_name='homerecommendedproduct',
            name='product',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
            preserve_default=False,
        ),
    ]
