# Generated by Django 5.1.15 on 2026-02-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_homerecommendedproduct_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarydocument',
            name='tab_index',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Мастер-каталог (New)'), (1, 'Техническая документация'), (2, 'Рекламные материалы'), (3, 'Сертификаты'), (4, 'Для проектировщиков'), (5, 'Средневольтное оборудование')]),
        ),
    ]
