# Generated by Django 5.1.15 on 2026-02-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_librarydocument_tab_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarydocument',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='library/icons/'),
        ),
    ]
