# Generated by Django 5.1.15 on 2026-02-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_librarydocument_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarydocument',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='library/en/'),
        ),
    ]
