# Generated by Django 5.1.15 on 2026-02-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('etim', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('vendor_code', models.CharField(db_index=True, max_length=64)),
                ('name', models.TextField()),
                ('full_name', models.TextField()),
                ('short_name', models.TextField()),
                ('etim', models.CharField(blank=True, max_length=64)),
                ('status_article', models.CharField(blank=True, max_length=64)),
                ('picture', models.URLField(blank=True)),
                ('raw', models.JSONField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
            ],
            options={
                'ordering': ['vendor_code'],
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('etim_feature', models.CharField(blank=True, max_length=64)),
                ('etim_value', models.CharField(blank=True, max_length=64)),
                ('etim_unit', models.CharField(blank=True, max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='catalog.product')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.property')),
            ],
        ),
    ]
