# Generated by Django 5.1.15 on 2026-02-05 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvalue',
            name='property',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='values', to='catalog.property'),
        ),
    ]
