# Generated by Django 5.1.15 on 2026-02-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_propertyvalue_property'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertyvalue',
            unique_together={('product', 'property')},
        ),
    ]
