# Generated by Django 5.1.15 on 2026-02-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_category_image_category_name_az_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name_az',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='name_ka',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
