# Generated by Django 5.1.15 on 2026-02-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_full_name_az_product_full_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvalue',
            name='value_az',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='value_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='value_ka',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
