# Generated by Django 5.1.15 on 2026-02-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_propertyvalue_value_az_propertyvalue_value_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
