# Generated by Django 5.1.15 on 2026-02-26 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='product_documents/')),
                ('title_ru', models.CharField(blank=True, default='', max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('title_az', models.CharField(blank=True, default='', max_length=255)),
                ('title_ka', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product document',
                'verbose_name_plural': 'Product documents',
                'ordering': ['sort_order', 'id'],
                'managed': True,
            },
        ),
    ]
